// ============================================================
// v2-memory.js — 客観記憶 / 主観記憶 / 記憶選別
// ============================================================

// ============================================================
// 客観記憶: state.situation.who[i].memories との同期
// ============================================================

/**
 * 客観記憶を登録（state + IndexedDB両方に保存）
 */
async function registerObjectiveMemory(charName, entry) {
  // state側に追加
  const charIdx = state.situation.who.findIndex(c => c.base.name === charName);
  if (charIdx >= 0) {
    if (!state.situation.who[charIdx].memories) state.situation.who[charIdx].memories = [];
    state.situation.who[charIdx].memories.push({
      id: entry.id || ('mem_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6)),
      summary: entry.summary,
      source: entry.source || [],
      scene: entry.scene || '',
      autoGenerated: true,
      timestamp: entry.timestamp || Date.now()
    });
  }
  // IndexedDB側に保存
  await saveObjectiveMemory(charName, entry);
}

/**
 * state.situation.who[i].memoriesからUI操作で記憶を追加
 */
function addMemoryEntry(charIdx, summary, autoGenerated, silent, source, scene) {
  autoGenerated = autoGenerated || false;
  silent = silent || false;
  const char = state.situation.who[charIdx];
  if (!char) return;
  if (!char.memories) char.memories = [];
  const mem = {
    id: 'mem_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6),
    summary: summary,
    source: source || [],
    scene: scene || '',
    autoGenerated: autoGenerated,
    timestamp: Date.now()
  };
  char.memories.push(mem);
  if (!silent) addLog('💭 記憶追加: ' + (char.base.name || 'Char' + charIdx) + ' — ' + summary.substring(0, 40), 'info');
  saveToStorage();
  // IndexedDBにも保存
  if (char.base.name) {
    saveObjectiveMemory(char.base.name, mem).catch(e => console.error('Memory save error:', e));
  }
}

function deleteMemoryEntry(charIdx, memId) {
  const char = state.situation.who[charIdx];
  if (!char || !char.memories) return;
  const before = char.memories.length;
  char.memories = char.memories.filter(m => m.id !== memId);
  if (char.memories.length < before) {
    addLog('🗑️ 記憶削除: ' + (char.base.name || 'Char' + charIdx), 'info');
    saveToStorage();
    renderCharacters();
    if (char.base.name) {
      deleteObjectiveMemory(char.base.name, memId).catch(e => console.error('Memory delete error:', e));
    }
  }
}

// ============================================================
// 記憶選別（Step 0で使用）
// ============================================================

/**
 * 全キャラの客観記憶から、次の生成に関連する記憶タグを選別
 * @param {string} recentText - 直近のキャラ本文合成テキスト
 * @returns {Promise<string[]>} 選別されたタグの配列
 */
async function selectRelevantMemories(recentText) {
  // 全キャラの客観記憶要約リストを構築
  let memoryList = '';
  state.situation.who.forEach(char => {
    if (!char.active || !char.memories || char.memories.length === 0) return;
    memoryList += '\n【' + (char.base.name || '?') + 'の記憶】\n';
    char.memories.forEach(mem => {
      const tags = (mem.source || []).join(', ');
      memoryList += '- [' + tags + '] ' + mem.summary + '\n';
    });
  });

  if (!memoryList.trim()) return [];

  const body = {
    system_instruction: { parts: [{ text:
      '以下はキャラクターの記憶要約リストです。各記憶には出典タグが付いています。\n\n' +
      memoryList +
      '\n\n【直近の物語テキスト】\n' + (recentText || '（なし — 初回生成）') +
      '\n\n【タスク】\n直近の展開を読み、次の物語生成に参照すべき過去の記憶を選んでください。\n\n' +
      '【選別基準】\n1. 人物の再会・対面（Who一致）\n2. 場所の再訪（Where一致）\n3. 因果関係（動機・原因）\n4. 状況の類似（戦闘・交渉等）\n5. 未解決の伏線\n\n' +
      '【出力形式】JSONのみ。\n{"tags": ["A-003-ルミア", "B-012-エルザ", ...]}'
    }] },
    contents: [{ role: 'user', parts: [{ text: '上記の記憶リストから関連する記憶タグを選別してください。' }] }],
    generationConfig: { temperature: 0.2, maxOutputTokens: 1024 },
    safetySettings: SAFETY_OFF
  };

  try {
    const data = await textApiFetch(body, '記憶選別');
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
    const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const result = safeParseJSON(cleaned, '記憶選別');
    return result.tags || [];
  } catch (e) {
    addLog('⚠️ 記憶選別失敗（全記憶を使用）: ' + e.message, 'warning');
    // フォールバック: 全タグを返す
    const allTags = [];
    state.situation.who.forEach(char => {
      if (!char.active || !char.memories) return;
      char.memories.forEach(mem => {
        if (mem.source) allTags.push(...mem.source);
      });
    });
    return allTags;
  }
}

// ============================================================
// 直近テキスト取得（キャラ本文DBから）
// ============================================================

/**
 * 現在のシーンの全キャラ本文を合成して直近テキストを生成
 * @param {number} maxChars - 最大文字数
 * @returns {Promise<string>}
 */
async function getRecentTextFromDB(maxChars) {
  maxChars = maxChars || 3000;
  try {
    const texts = await loadCharacterTextsByScene(state.currentScene.key);
    if (!texts || texts.length === 0) return '';

    // 全段落をイベント番号順に統合
    const allParas = [];
    texts.forEach(ct => {
      if (!ct.paragraphs) return;
      Object.entries(ct.paragraphs).forEach(([tag, para]) => {
        const r = resolveTag(tag);
        if (r) {
          allParas.push({ tag, num: parseInt(r.num, 10), char: r.entity, text: para.text || '' });
        }
      });
    });
    allParas.sort((a, b) => a.num - b.num || a.char.localeCompare(b.char));

    let result = '';
    for (const p of allParas) {
      const line = '[' + p.tag + '] ' + p.text + '\n\n';
      if (result.length + line.length > maxChars) break;
      result += line;
    }
    return result;
  } catch (e) {
    console.error('getRecentTextFromDB error:', e);
    return '';
  }
}
